name: AzureDeploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Install Az
       shell: pwsh
       run: "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; Install-Module -Name Az -AllowClobber -Force; get-module -listavailable"
     - name: Get Az Ps Modules
       shell: pwsh
       run: "Get-Module -listavailable"
     - name: Checking variables
       shell: pwsh
       env:
        user: ${{ secrets.USER }}
        pwd: ${{ secrets.PWD }}
        tenant: ${{ secrets.TENANT }}
       run: "[string]$changestart = 'HEAD'; [string]$changeend = 'HEAD~1'; $changeset = (git diff --name-only origin/master $changestart $changeend); Write-Host 'The change set is:'$changeset"
