name: AzureDeploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - name: Install Az
     shell: pwsh
     run: "Set-PSRepository -Name PSGallery -InstallationPolicy Trusted; Install-Module -Name Az -AllowClobber -Force; get-module -listavailable"
     - name: Get Az Ps Modules
     run: Get-Module -listavailable
