name: AzureDeploy

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
      env:
       user: ${{ secrets.USER }}
       pwd: ${{ secrets.PWD }}
       tenant: ${{ secrets.TENANT }}
    - name: Executing Pipeline Script
      shell: pwsh
      run: pwsh -command "Write-host $env:user"
