name: AzureDeploy

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: checking shell
    uses: actions/checkout@v1
    shell: powershell
      env:
       user: ${{ secrets.USER }}
       pwd: ${{ secrets.PWD }}
       tenant: ${{ secrets.TENANT }}
      run: powershell -command "Install-Module -Name Az -Force -AllowClobber -Verbose"
    - name: running another line
      run: powershell -File -Filepath "https://raw.githubusercontent.com/krnese/AzureDeploy/master/pipeline.ps1"
