name: AzureDeploy

on: [push]

jobs:
  build:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      env:
       user: ${{ secrets.USER }}
       pwd: ${{ secrets.PWD }}
      run: powershell -command "write-host '$($env:user)'"
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
