name: AzureDeploy

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Firing pwsh script in Docker container
      env:
       user: ${{ secrets.USER }}
       pwd: ${{ secrets.PWD }}
       tenant: ${{ secrets.TENANT }}
      run: echo Hello ${TENANT}
